import "@/app/globals.css";
import Header from "../../components/webapp/Header";
import Footer from "@/components/webapp/Footer";
import Modal from "@/components/dashboard/common/Modal";
import { museoLight } from "@/utils/font";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${museoLight.className} scroll-smooth`}>
        <Modal />
        <header>
          <Header />
        </header>
        {children}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
